### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by Archie-Yang** [microsoft/vscode-serial-monitor#148]
Type: Feature Request

Please make this extension ARM64 supported, version 0.10.231102001 show error during activation:

```log
2023-11-07 22:15:04.159 [info] ExtensionService#_doActivateExtension ms-vscode.vscode-serial-monitor, startup: false, activationEvent: 'onView:vscode-serial-monitor.monitor0'
2023-11-07 22:15:04.275 [error] Activating extension ms-vscode.vscode-serial-monitor failed due to an error:
2023-11-07 22:15:04.275 [error] Error: No native build was found for platform=win32 arch=arm64 runtime=electron abi=116 uv=1 armv=8 libc=glibc node=18.15.0 electron=25.9.2
    loaded from: c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\node_modules\@serialport\bindings-cpp

	at load.path (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\node_modules\node-gyp-build\index.js:1:3225)
	at load (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\node_modules\node-gyp-build\index.js:1:710)
	at Object.<anonymous> (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\node_modules\@serialport\bindings-cpp\dist\load-bindings.js:1:593)
	at o._compile (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at r._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:5647)
	at c._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:29431)
	at t._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:35262)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\node_modules\@serialport\bindings-cpp\dist\darwin.js:1:348)
	at o._compile (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at r._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:5647)
	at c._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:29431)
	at t._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:35262)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\node_modules\@serialport\bindings-cpp\dist\index.js:1:783)
	at o._compile (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at r._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:5647)
	at c._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:29431)
	at t._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:35262)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\node_modules\serialport\dist\serialport.js:1:217)
	at o._compile (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at r._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:5647)
	at c._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:29431)
	at t._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:35262)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\node_modules\serialport\dist\index.js:1:1191)
	at o._compile (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at r._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:5647)
	at c._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:29431)
	at t._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:35262)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at 6605 (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\extension.js:1:478905)
	at o (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\extension.js:1:800518)
	at 6406 (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\extension.js:1:34142)
	at o (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\extension.js:1:800518)
	at 7348 (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\extension.js:1:30972)
	at o (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\extension.js:1:800518)
	at 5000 (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\extension.js:1:32877)
	at o (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\extension.js:1:800518)
	at 8604 (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\extension.js:1:468310)
	at o (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\extension.js:1:800518)
	at 7258 (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\extension.js:1:461328)
	at o (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\extension.js:1:800518)
	at c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\extension.js:1:801255
	at Object.<anonymous> (c:\Users\Archie\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.10.231102001\dist\extension.js:1:801281)
	at o._compile (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at r._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:5647)
	at c._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:29431)
	at t._load (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:35262)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
	at h.vb (c:\Users\Archie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:30610)
	at async Promise.all (index 0)
```

**Comment by gcampbell-msft** [comment]
Seems like this is an external issue on the serial port library: https://github.com/serialport/node-serialport/issues/2570.

**Comment by bjornh2** [comment]
I have the same error on my Lenovo Ideapad 5x:
I found this in the log (Show Logs -> Extension Host):
2024-12-16 20:38:39.627 [info] ExtensionService#_doActivateExtension ms-vscode.vscode-serial-monitor, startup: false, activationEvent: 'onView:vscode-serial-monitor.monitor0'
2024-12-16 20:38:39.678 [error] Activating extension ms-vscode.vscode-serial-monitor failed due to an error:
2024-12-16 20:38:39.678 [error] Error: No native build was found for platform=win32 arch=arm64 runtime=electron abi=128 uv=1 armv=8 libc=glibc node=20.18.1 electron=32.2.6
loaded from: c:\Users\bjorn.vscode\extensions\ms-vscode.vscode-serial-monitor-0.13.1\dist\node_modules@serialport\bindings-cpp

**Comment by scarolan** [comment]
Hello, is there any workaround while you sort this out?

**Comment by bjornh2** [comment]
My workaround are to download an Windows app, Serial Debug Assistant https://apps.microsoft.com/detail/9NBLGGH43HDM and run it outside of VS code.

**Comment by scarolan** [comment]
> My workaround are to download an Windows app, Serial Debug Assistant https://apps.microsoft.com/detail/9NBLGGH43HDM and run it outside of VS code.

I ended up just using good old fashioned PuTTY instead, which does have an ARM64 build.
